### ISSUE TITLE
Update to recent sveltekit changes and other things

### ISSUE THREAD

**Issue by amr3k** [kudadam/svelte-cusdis#1]
Hi, thanks for creating this great library.

I made a fork to suggest some edits, but when I tried to install dependencies, I found some errors related to the breaking changes in sveltekit post 405 release.

So my suggestion is to upgrade all dependencies and alter the file structure accordingly.

I have the project cloned on my device, if you like, I can do these changes and open a PR.

**Comment by lubiah** [comment]
Hello @amr3k , I haven't updated the library after the breaking changes. This is because am in school and concentrating on my exams. 


I would be glad if you can fix all the bugs and submit a pull request

**Comment by amr3k** [comment]
No worries, good luck in school, I'm going to do those tonight.

**Comment by lubiah** [comment]
Thanks a lot

**Comment by lubiah** [comment]
@amr3k 
Just a quick question, do you think it would be better to re-code the module in typescript instead of JavaScript?

**Comment by amr3k** [comment]
To be honest, I don't think so.

The library is tiny, the sugary benefits of typescript that improves DX, can be done using jsDoc

I'm already working on it right now.

**Comment by lubiah** [comment]
Oh okay, then I guess JavaScript is the best way to go

**Comment by amr3k** [comment]
Also, while we're here, I feel like `attrs` should be exploded to props.

So instead of `attrs.host` , it becomes just `host`.

What do you think?

**Comment by lubiah** [comment]
Yeah, that would be great. 
I thought of it this way when I was creating the library but the port of it in React was using this methodology.
It would be great to split it into props
