### ISSUE TITLE
SSR 

### ISSUE THREAD

**Issue by korzh875** [kudadam/svelte-cusdis#2]
Hello

thanks for the library

but it doesn't work in some cases

for example, when going to other pages with ssr

here is the emulation

or press the restart button or add something to the template and save, the comment form disappears

https://stackblitz.com/edit/daisyui-sveltekit-ubtpn9?file=package.json

**Comment by lubiah** [comment]
Hi, when navigating to other pages in SSR, the library works. You aren't actually navigating to another page in the example you provided.

**Comment by korzh875** [comment]
this is an emulation of moving to another page

**Comment by korzh875** [comment]
can you make it so that when the component is restarted, it is initialized again?

https://svelte.dev/repl/286559382580492c8288e53a3597d7e1?version=3.28.0

**Comment by lubiah** [comment]
Alright, I will take a look at it today

**Comment by lubiah** [comment]
Hello @korzh875 , I finally fixed it, it's working as intended.

![preview](https://user-images.githubusercontent.com/63173187/236924851-93d91418-9427-4d4f-8a58-5f1b69e946d1.gif)

**Comment by lubiah** [comment]
I've published a new version with the problem fixed

**Comment by korzh875** [comment]
not working

https://stackblitz.com/edit/daisyui-sveltekit-bhcewp?file=package.json 0.0.5
https://stackblitz.com/edit/daisyui-sveltekit-evnxjl?file=package.json 0.0.6

the new version of the package is not installed
or the installation fails

**Comment by lubiah** [comment]
@korzh875 , I think it's working, please take a look at the readme. There was another issue open which made me make changes to the whole library. 

In the link you also sent, you are using version 0.0.5 and I just published 0.0.6

**Comment by korzh875** [comment]
https://stackblitz.com/edit/daisyui-sveltekit-evnxjl?file=package.json

0.0.6 Version not working

Do Not install correctly

**Comment by lubiah** [comment]
https://github.com/kudadam/svelte-cusdis#props. Use the props here instead. It doesn't use the attr props again

**Comment by korzh875** [comment]
like this?

`<Cusdis
 attrs = {{
     appId: "2f49c941-a723-4350-a9eb-cad6fab4772b",
     pageId: "1",
     pageUrl: "https:localhost:3000",
     pageTitle: "Svelte Cusdis"
 }}
/>`

**Comment by korzh875** [comment]
did you publish the package correctly!?

Why did you re-upload the project to GitHub? I do not see the changes that you made, because everything has changed!

**Comment by korzh875** [comment]
Please open this issue until it is resolved

**Comment by lubiah** [comment]
I had to do a force push to github

**Comment by kudadam** [comment]
<Cusdis
appId="2f49c941-a723-4350-a9eb-cad6fab4772b"
pageId="demo"
Url="demo"
pageTitle="demo"
/>

**Comment by kudadam** [comment]
<Cusdis
appId="2f49c941-a723-4350-a9eb-cad6fab4772b"
pageId="demo"
Url="demo"
pageTitle="demo"
/>

**Comment by korzh875** [comment]
check if your library is correct, as it's in the comment above where version 0.0.6 just doesn't work

or show how the component should be initialized

**Comment by lubiah** [comment]
```
<Cusdis
appId="2f49c941-a723-4350-a9eb-cad6fab4772b"
pageId="demo"
Url="demo"
pageTitle="demo"
/>
```

**Comment by lubiah** [comment]
Unless evening time, right now I'm at work

**Comment by korzh875** [comment]
https://stackblitz.com/edit/daisyui-sveltekit-wgtelw?file=src%2Froutes%2F%2Bpage.svelte

doesnt work :(

**Comment by korzh875** [comment]
https://www.npmjs.com/package/svelte-cusdis/v/0.0.5?activeTab=code compare https://www.npmjs.com/package/svelte-cusdis/v/0.0.6?activeTab=code

wrong package.json

**Comment by lubiah** [comment]
Hi, thanks for alerting me, I have seen where the mistake is originating from, I will fix it this evening

**Comment by lubiah** [comment]
@korzh875 , I have fixed it, can you confirm it on your end for me

**Comment by korzh875** [comment]
works fine

**Comment by korzh875** [comment]
pls remove  console.log("Destroyed");

**Comment by lubiah** [comment]
oh sorry😂😂

**Comment by lubiah** [comment]
Done
